name: ci_test
channels:
  - conda-forge

dependencies:
  - git
  - python
  - beautysh==5.0.2
  - black==19.3b0
  - flake8==3.7.8
  - flake8-black==0.1.1
  - git-sizer==1.3.0
  - make
  - pyexasol
  - pylint==2.3.1
  - pytest==5.1.2
  - pytest-html==2.0.0
  - ripgrep==11.0.2
  - shellcheck==0.7.0
  - shyaml
  - sqlparse==0.3.0
