CREATE SCHEMA SANDBOX;

CREATE TABLE SANDBOX.DUMMY_TABLE (
    TEST_STRING      VARCHAR(128) UTF8,
    TEST_DECIMAL     DECIMAL(18,0),
    TEST_TIMESTAMP   TIMESTAMP,
    DUMMY_CHAR  VARCHAR(128) UTF8,
    aWiErD_NamiNG   VARCHAR(2000000) UTF8
);